### ISSUE TITLE
Dont See resource overlay

### ISSUE THREAD

**Issue by PengH38** [BedWarMod/BedWar#2]

**Comment by CalMWolfs** [comment]
Hey sorry that you are experiencing this, I currently have no way to test/fix the mod but if you can provide a bit more detail into what is broken I can probably fix it quicker in future

**Comment by unparted** [comment]
Yea I've noticed that trap overlay also doesn't work. Along with the party match stats. In a fours game it said my teammate got 4 beds and like 14 finals. Before it was working just fine, but I took a week break and I came back to it not working. If you would like me to record a video or something showing the bug just let me know. Its pretty consistent.

**Comment by CalMWolfs** [comment]
They probably changed some chat message that the mod user to detect events. So a video of the issue occurring and probably the beginning of the game would be good. In addition the game logs while it happens would be useful. If you want you can dm it to me on discord

**Comment by unparted** [comment]
Oh yea with the new update it probably messed up the mod, ill record a video really quick and send the logs.

**Comment by CalMWolfs** [comment]
@PengH38 thid issue should be fixed the next time you restart your game, please let me know if it isn't or something else is not working
