### ISSUE TITLE
Bed Break message in castle doesn't match Bed Break regex

### ISSUE THREAD

**Issue by phiwijo** [BedWarMod/BedWar#3]
A bed break message like this (from castle) doesn't match the regex and I get the nice message: "Warning! Bed Break message did not match!
Please report this bed break message on the github so your stats can be more accurate :)"
Here is a bed break message that causes it:
With color codes:
`§r§f§lBED DESTRUCTION > §r§7§r§cRed §r§cSquare §r§7was bed §r§e#1,413 §r§7destroyed by §r§9SmallFlowerMan§r§7!§r`
Without:
`BED DESTRUCTION > Red Square was bed #1,413 destroyed by SmallFlowerMan!`
Probably an easy fix, but too lazy to do it myself :D

**Comment by CalMWolfs** [comment]
I think i just fixed this [on my end](https://github.com/BedWarMod/BedWar-Repo/commit/db0415496cee427851c408e11a92e88551ba0a83), on your next game restart it may work but if not let me know by replying here

**Comment by phiwijo** [comment]
Tested it with /ct simulate and it seems to work (castle is out of rotation rn and private castle doesn't exist so it should work fine)

**Comment by phiwijo** [comment]
Ty :D
